[build]
builder = "nixpacks"

[deploy]
startCommand = "npm run predeploy && npm run drizzle:push && node dist/src/main.js"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[deploy.envs]
NODE_ENV = "production" 
